version: '2'
services:
  db:
    image: docker.io/bitnami/mariadb:10.6
    environment:
      # ALLOW_EMPTY_PASSWORD is recommended only for development.
      - MARIADB_USER=bn_moodle
      - MARIADB_PASSWORD=abcd
      - MARIADB_ROOT_PASSWORD=abcd
      - MARIADB_DATABASE=bitnami_moodle
      - MARIADB_CHARACTER_SET=utf8mb4
      - MARIADB_COLLATE=utf8mb4_unicode_ci
    volumes:
      - 'mariadb_data:/bitnami/mariadb'
  moodle:
    build: .
    ports:
      - '80:8080'
      - '443:8443'
    environment:
      - PHP_OUTPUT_BUFFERING=8193
      - MOODLE_DATABASE_HOST=db
      - MOODLE_DATABASE_PORT_NUMBER=3306
      - MOODLE_DATABASE_USER=bn_moodle
      - MOODLE_DATABASE_PASSWORD=abcd
      - MOODLE_DATABASE_NAME=bitnami_moodle
      # ALLOW_EMPTY_PASSWORD is recommended only for development.
#      - ALLOW_EMPTY_PASSWORD=yes
    volumes:
      - 'moodle_data:/bitnami/moodle'
      - 'moodledata_data:/bitnami/moodledata'
    depends_on:
      - db


  phpmyadmin:
    image: phpmyadmin
    ports:
      - 8090:80
    environment:
      PMA_USER: root
      PMA_PASSWORD: abcd
      PMA_HOSTS: db
    restart: unless-stopped

volumes:
  mariadb_data:
    driver: local
  moodle_data:
    driver: local
  moodledata_data:
    driver: local
