version: '3'
services:
  moodle:
    build:
      context: .
      args:
        PLUGIN_VERSION: main
        MOODLE_VERSION: 4.2
    ports:
      - '8000:8080'
    environment:
      PHP_OUTPUT_BUFFERING: 8192
      PHP_POST_MAX_SIZE: 2048M
      PHP_UPLOAD_MAX_FILESIZE: 2048M
      MOODLE_DATABASE_HOST: db_moodle
      MOODLE_DATABASE_PORT_NUMBER: 3306
      MOODLE_DATABASE_USER: moodle
      MOODLE_DATABASE_PASSWORD: moodle
      MOODLE_DATABASE_NAME: moodle
      BITNAMI_DEBUG: true
      USER_NAME: student,manager
      USER_PASSWORD: Student1234!1234,Manager1234!1234
      USER_ROLE: manager,false
      DEVELOP_DONT_INSTALL_PLUGINS: true
    volumes:
      - /home/markus/moodle:/bitnami/moodle
      - moodle_moodledata:/bitnami/moodledata
      - moodle_moodledata_phpu:/bitnami/moodledata_phpu
    depends_on:
      - db_moodle
    restart: unless-stopped

  db_moodle:
    image: docker.io/bitnami/mariadb:10.6
    environment:
      MARIADB_USER: moodle
      MARIADB_PASSWORD: moodle
      MARIADB_ROOT_PASSWORD: root_pw
      MARIADB_DATABASE: moodle
      MARIADB_CHARACTER_SET: utf8mb4
      MARIADB_COLLATE: utf8mb4_unicode_ci
    volumes:
      - db_moodle_data:/bitnami/mariadb
    restart: unless-stopped

  phpmyadmin:
    image: phpmyadmin
    ports:
      - 8090:80
    environment:
      PMA_USER: root
      PMA_PASSWORD: abcd
      PMA_HOSTS: db_moodle
    restart: unless-stopped

volumes:
  moodle_moodledata_phpu:
    driver: local
  moodle_moodledata:
    driver: local
  db_moodle_data:
    driver: local
